# Generated by Django 3.2.13 on 2022-04-23 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EpidmicPrevention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, null=True)),
                ('phone', models.CharField(max_length=12, null=True)),
                ('identify', models.CharField(max_length=20, null=True)),
                ('adress', models.CharField(max_length=20, null=True)),
                ('time', models.CharField(max_length=10, null=True)),
                ('epidmedicStation', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
