# Generated by Django 3.2.13 on 2022-04-24 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_epidmicprevention'),
    ]

    operations = [
        migrations.CreateModel(
            name='Healthy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, null=True)),
                ('phone', models.CharField(max_length=12, null=True)),
                ('password', models.CharField(max_length=20, null=True)),
                ('Identify', models.CharField(max_length=20, null=True)),
                ('address', models.CharField(max_length=20, null=True)),
                ('status', models.CharField(max_length=20, null=True)),
                ('temperature', models.CharField(max_length=5, null=True)),
            ],
        ),
    ]
