# Generated by Django 3.2.13 on 2022-04-24 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_healthy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='healthy',
            old_name='password',
            new_name='comment',
        ),
    ]
