# Generated by Django 3.2.13 on 2022-04-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_userinfo_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10, null=True)),
                ('password', models.CharField(max_length=10, null=True)),
                ('avatar', models.ImageField(default='avatar3.jpg', upload_to='picture')),
            ],
        ),
    ]
