# Generated by Django 3.2.13 on 2022-04-25 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='username',
            new_name='usernames',
        ),
    ]
