# Generated by Django 3.2.13 on 2022-05-07 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0010_remove_new_publisher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='new',
            old_name='time',
            new_name='Date',
        ),
    ]
