# Generated by Django 3.2.13 on 2022-05-09 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0013_new_idd'),
    ]

    operations = [
        migrations.CreateModel(
            name='JuMin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5, null=True)),
                ('identify', models.CharField(max_length=20, null=True)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('address', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
