# Generated by Django 3.2.13 on 2022-05-09 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0014_jumin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='idd',
        ),
    ]
