# Generated by Django 3.2.13 on 2022-05-17 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0016_selfchecked'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stationinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station', models.CharField(max_length=10, null=True)),
                ('idNum', models.CharField(max_length=2, null=True)),
                ('longitude', models.CharField(max_length=10, null=True)),
                ('latitude', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
