# Generated by Django 3.2.13 on 2022-05-17 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0017_stationinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stationinfo',
            name='idNum',
        ),
    ]
