# Generated by Django 3.2.13 on 2022-05-18 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0018_remove_stationinfo_idnum'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hardware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hardWareName', models.CharField(max_length=10, null=True)),
                ('temperature', models.CharField(max_length=5, null=True)),
                ('Rnum', models.IntegerField(max_length=5, null=True)),
                ('Cnum', models.IntegerField(max_length=5, null=True)),
                ('picture', models.ImageField(upload_to='picture')),
            ],
        ),
    ]
