# Generated by Django 3.2.13 on 2022-05-18 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0020_alter_hardware_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardware',
            name='picture',
            field=models.ImageField(default='avatar4.jpg', null=True, upload_to='picture'),
        ),
    ]
